# Basic Example

In [1]:
import numpy as np

In [30]:
nx, ny = (3, 6)
x = np.linspace(0, 10, nx)
y = np.linspace(0, 10, ny)
xv, yv = np.meshgrid(x, y)

In [31]:
x

array([ 0.,  5., 10.])

In [32]:
y

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
xv

array([[ 0.,  5., 10.],
       [ 0.,  5., 10.],
       [ 0.,  5., 10.],
       [ 0.,  5., 10.],
       [ 0.,  5., 10.],
       [ 0.,  5., 10.]])

In [34]:
yv

array([[ 0.,  0.,  0.],
       [ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.]])

In [36]:
xv.shape, yv.shape

((6, 3), (6, 3))

In [24]:
xv, yv = np.meshgrid(x, y, sparse=True)  # make sparse output arrays

In [25]:
xv

array([[0. , 0.5, 1. ]])

In [26]:

yv

array([[0. ],
       [0.5],
       [1. ]])