In [1]:
import numpy as np

# ndarray

In [5]:
A = np.array([1,2,3,4])
print(type(A))

<class 'numpy.ndarray'>


In [6]:
A.dtype

dtype('int64')

In [4]:
type(A)

numpy.ndarray

In [32]:
B = np.arange(1, 28)
print(B)
print("")
B=B.reshape(3, 3, 3)
print(B)
print(type(B))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>


In [12]:
B.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
B.shape

(9,)

In [42]:
A[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [43]:
A.mean()

50.5

In [44]:
np.average(A)

50.5

In [70]:
A = np.arange(1, 101)
A = A.reshape(10, -1)
"shape", A.shape, "len", len(A), "size", A.size

('shape', (10, 10), 'len', 10, 'size', 100)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [74]:
A = np.arange(1, 101)
A = A.reshape(10, -1)
A[:, 0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [75]:
A[:,[0]]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [96]:
A = np.random.randint(-10, 10, 20)
B = np.random.randint(50, 100, 20)

In [112]:
C = np.concatenate(([A], [B]), axis=1)
print(C.shape)
C

(1, 40)


array([[-10,   3,  -7, -10,   1,   6,  -1,   4,   2,  -7,   3,  -3,  -6,
          1,   4,   5,  -4,   6,  -7,   2,  51,  57,  84,  69,  71,  54,
         58,  70,  83,  96,  89,  55,  71,  87,  70,  70,  99,  56,  91,
         82]])

In [113]:
C = np.concatenate((A, B), axis=0)
print(C.shape)
C

(40,)


array([-10,   3,  -7, -10,   1,   6,  -1,   4,   2,  -7,   3,  -3,  -6,
         1,   4,   5,  -4,   6,  -7,   2,  51,  57,  84,  69,  71,  54,
        58,  70,  83,  96,  89,  55,  71,  87,  70,  70,  99,  56,  91,
        82])

In [115]:
C = np.concatenate((A.T, B.T), axis=0)
print(C.shape)
C

(40,)


array([-10,   3,  -7, -10,   1,   6,  -1,   4,   2,  -7,   3,  -3,  -6,
         1,   4,   5,  -4,   6,  -7,   2,  51,  57,  84,  69,  71,  54,
        58,  70,  83,  96,  89,  55,  71,  87,  70,  70,  99,  56,  91,
        82])

In [117]:
A.shape, B.shape

((20,), (20,))

# Broadcasting

In [125]:
A = np.ones((3,3))
B = np.array([3,3,3])
C = np.array([2,2,2])
D = np.array([5,5])

In [120]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
B

array([3, 3, 3])

In [122]:
A + B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [124]:
A + C.T

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [126]:
A + D

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 